### ISSUE TITLE
Add Registeration CRUD

### ISSUE THREAD

**Issue by Quintasan** [MaximumSquotting/rajdownik#1]
Model attributes:
- `name`: String
- `student_id`: String
- `accepted`: Boolean
- `paid`: Boolean
- `boarded_at_source`: Boolean
- `boarded_at_destination`: Boolean
- `created_at`: DateTime
- `updated_at`: DateTime

The last two are created automatically. This task is done when you can perform CRUD operations via web interface.

**Comment by bblazik** [comment]
Installed rails
bundle install
Error while bundle install about FFI gem, remove from cache installed again. 
Probably You mean Registration model. 
Generate model
